name: vasttrafik_nara
description: Another Västtrafik travel planner

publish_to: 'none'

version: 1.3.0+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: any
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_tags: "^0.4.9+1"
  location: ^3.2.1
  intl: any
  latlong: ^0.6.1
  device_info: ^1.0.0
  auto_size_text: ^2.1.0
  shared_preferences: ^0.5.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
